# Generated by Django 3.2.14 on 2022-07-13 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snsapp', '0004_freecomments_freepost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freecomments',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='snsapp.freepost'),
        ),
    ]
